package com.jeex.sci.test;

import org.springframework.stereotype.Component;

import com.jeex.sci.CacheEvict;
import com.jeex.sci.Cacheable;

@Component
public class BlackListDaoImpl implements BlackListDao {
	
	// Key is set manually, not recommended
	@Cacheable(namespace="BlackList", key="1:222.231.23.13")
	public int searchBlackListCount(BlackListQuery query) {
		return 100;
	}
	
	// Key is set from Java Bean properties from the first argument
	@Cacheable(namespace="BlackList", keyProperties={"infoType", "info"})
	public int searchBlackListCount2(BlackListQuery query) {
		return 100;
	}
	
	// Key is generated by the a class implements CacheKeyGenerator
	@Cacheable(namespace="BlackList", keyGenerator="com.ywpay.cache.BlackListQueryCacheKeyGenerator")
	public int searchBlackListCount3(BlackListQuery query) {
		return 100;
	}
	
	// Delete all the keys in the specified namespace
	@CacheEvict(namespace="BlackList")
	public void evictAll() {
		
	}
	
	// Delete a key
	@CacheEvict(namespace="BlackList", keyProperties={"infoType", "info"})
	public void evict(BlackListQuery query) {
		
	}

}
